### ISSUE TITLE
'rem' or 'px' option

### ISSUE THREAD

**Issue by iamfrntdv** [KolceThompsonCo/postcss-lh#9]
It would be great if there was an option to choose between pixels or rems.

**Comment by jameskolce** [comment]
Hey @admdh Thanks for the suggestion, I'll add this option for the next version!

**Comment by jameskolce** [comment]
@admdh I'm about to start with this, I just have a quick but important question: Why exactly do you need pixels instead of rems? Is it for browser support (IE8)? or just pixel precision?

The implementation using rems is pretty elegant since it doesn't require the font-size and it responds to media queries, also the relation between line-height and rems is pretty close, which is nice. To produce pixels I would need to get the root font-size and multiply the result in rems to get pixels, it's not a big deal to do that, but also the sizes created using `lh` would be static, you can see the issue in this another repository: https://github.com/markgoodyear/postcss-vertical-rhythm/issues/8 Which one of the reasons I created this project instead of using `postcss-vertial-rhythm` (you can see my comment at the end of that issue).

I'm willing to add this feature, it's exciting to solve problems! I just wanted to make sure you know the implications of the use of pixels in this case. So let me know, thanks.

**Comment by admdh** [comment]
I was trying to use ems and rems but I end up with pixels. I saw a lot of projects used ems or rems just like pixels. I mean there are still a lot of developers thinking in pixels. Another point is that from project to project rem can be different somewhere 1rem = 16px, somewhere 1rem = 14px.. As for me when I see 16px i exactly know how much is that. 

I'm not against rem or ems, i know why the are better than pixel, but i still prefer pixels) may be someday i will use rems)

Thank you for your quick answer!;)

**Comment by jameskolce** [comment]
Oh I understand! The use of rems and specially ems is a little confusing sometimes but trust me, when comes to the vertical rhythm you don't have to think in precise measurements (px) but in proportions to something else, since it's all about aesthetics. The main thing for vertical rhythm in a website is the line height, so all you have to think of is "how many line heights do I need" instead of "how many pixels do I need".

When you say `margin-bottom: 2lh` you shouldn't think of it like "add a margin of 48px if the font-size is 16px and the line-height is 1.5" but instead "add a margin of two times the line height, whatever the line-height is and whatever the font-size is".

I have to confess that when I started the project, I was still a little confused with the idea of knowing the pixel equivalent to 1rem as well but turns out you don't have to because of the reason I said before. 

So yeah, it's tempting to try to use pixels for margins, heights, and all that stuff, but you will get aesthetically better results by using proportions. Sorry if this has turned into a design issue more than a development one, I just wanted to present the design-related information about the use of pixels which should be used with caution in this case. However, I accept the suggestion and will implement the option you mention because there might be edge cases!

**Comment by jameskolce** [comment]
Sorry for the LONG delay, today I decided to continue with this but saw a lot of extra things that I would have to do to produce px, and I'm not sure about supporting it on this project, but you can check out this one: https://github.com/markgoodyear/postcss-vertical-rhythm which uses px. I still think that px is not an ideal solution but that project works for that.
I'll close this for now, but if someone submits a PR then I will consider it. Sorry for such a long wait, maybe I should have seen this first 😅
